version: 2
updates:
  - package-ecosystem: nuget
    directory: /Backup
    target-branch: preview
    schedule:
      interval: weekly
    groups:
      nuget-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /Frontend-2.0
    target-branch: preview
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: preview
    schedule:
      interval: weekly
    groups:
      actions-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /Backup/Backup.Server.Api
    target-branch: preview
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /Backup/Backup.Agent.Worker
    target-branch: preview
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /Frontend-2.0
    target-branch: preview
    schedule:
      interval: weekly
