import { useDeferredValue, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Download, Search } from 'lucide-react'
import { toast } from 'sonner'

import { downloadArtifact, getArtifacts } from '@/entities/artifact/api'
import type { BackupArtifact } from '@/entities/artifact/model/types'
import { getJobs } from '@/entities/job/api'
import { formatBytes, formatDateTime } from '@/shared/lib/format'
import { useI18n } from '@/shared/i18n'
import { useLiveQueryOptions } from '@/shared/lib/useLiveQueryOptions'
import { Button } from '@/shared/ui/Button'
import { queryKeys } from '@/shared/lib/query'
import { Card } from '@/shared/ui/Card'
import { EmptyState } from '@/shared/ui/EmptyState'
import { Input } from '@/shared/ui/Input'
import { SectionHeading } from '@/shared/ui/SectionHeading'

export function ArtifactsPage() {
  const { t } = useI18n()
  const liveQueryOptions = useLiveQueryOptions()
  const [search, setSearch] = useState('')
  const [downloadingArtifactId, setDownloadingArtifactId] = useState<string | null>(null)
  const deferredSearch = useDeferredValue(search)

  const artifactsQuery = useQuery({
    queryKey: queryKeys.artifacts,
    queryFn: () => getArtifacts(),
    ...liveQueryOptions,
  })
  const jobsQuery = useQuery({
    queryKey: queryKeys.jobs,
    queryFn: () => getJobs('all'),
    ...liveQueryOptions,
  })

  const jobMap = new Map((jobsQuery.data ?? []).map((job) => [job.id, job]))
  const artifacts = artifactsQuery.data ?? []
  const downloadMutation = useMutation({
    mutationFn: async (artifact: BackupArtifact) => {
      setDownloadingArtifactId(artifact.id)
      await downloadArtifact(artifact)
    },
    onSuccess: () => {
      toast.success(t('Artifact download started'))
    },
    onError: (error) => {
      toast.error(error instanceof Error ? error.message : t('Artifact download failed'))
    },
    onSettled: () => {
      setDownloadingArtifactId(null)
    },
  })
  const searchValue = deferredSearch.trim().toLowerCase()
  const filteredArtifacts = !searchValue
    ? artifacts
    : artifacts.filter((artifact) =>
        [artifact.fileName, artifact.objectKey, artifact.checksum, artifact.jobId]
          .join(' ')
          .toLowerCase()
          .includes(searchValue),
      )

  return (
    <div className="space-y-8">
      <SectionHeading
        eyebrow={t('Artifacts')}
        title={t('Stored backup objects')}
        description={t('Review resulting files, object keys and checksums generated by backup jobs before wiring restore flows.')}
      />

      <Card className="max-w-md">
        <div className="relative">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-800/60" />
          <Input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            className="pl-10"
            placeholder={t('Search by filename, key, checksum')}
          />
        </div>
      </Card>

      {filteredArtifacts.length ? (
        <Card className="overflow-hidden p-0">
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="bg-surface-100 text-ink-800">
                <tr>
                  {['File name', 'Object key', 'Size', 'Checksum', 'Created', 'Job', 'Action'].map((label) => (
                    <th key={label} className="px-4 py-3 font-medium">
                      {t(label)}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {filteredArtifacts.map((artifact) => (
                  <tr key={artifact.id} className="border-t border-surface-200">
                    <td className="px-4 py-3 font-medium text-ink-950">{artifact.fileName}</td>
                    <td className="max-w-sm px-4 py-3 text-ink-800">{artifact.objectKey}</td>
                    <td className="px-4 py-3 text-ink-800">{formatBytes(artifact.size)}</td>
                    <td className="px-4 py-3 font-mono text-xs text-ink-800">{artifact.checksum}</td>
                    <td className="px-4 py-3 text-ink-800">{formatDateTime(artifact.createdAt)}</td>
                    <td className="px-4 py-3 text-ink-800">
                      {jobMap.get(artifact.jobId)?.id.slice(0, 8) ?? artifact.jobId.slice(0, 8)}
                    </td>
                    <td className="px-4 py-3">
                      <Button
                        size="sm"
                        variant="secondary"
                        disabled={downloadMutation.isPending && downloadingArtifactId === artifact.id}
                        onClick={() => downloadMutation.mutate(artifact)}
                      >
                        <Download className="h-3.5 w-3.5" />
                        {downloadMutation.isPending && downloadingArtifactId === artifact.id
                          ? t('Preparing')
                          : t('Download')}
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      ) : (
        <EmptyState title={t('No artifacts found')} description={t('The current dataset has no backup objects matching the active filter.')} />
      )}
    </div>
  )
}
